version: 2
project_name: kickstartsh

builds:
  - main: ./cmd/kickstart
    binary: kickstartsh
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: "asc"